title: Maxim Manns
description: >-
  Welcome to my personal website and GitHub page.

baseurl: ""
url: "https://maximmanns.github.io"
github_username: MaximManns

# Build settings
theme: minima
plugins:
  - jekyll-feed
